application.mail.lateloans.message=Atenção! Você tem o empréstimo atrasado. Por favor, devolver o livro o quanto antes!
application.mail.default-remetent=mail@library-api.com

spring.mail.protocol = smtp
spring.mail.host = smtp.mailtrap.io
spring.mail.port = 2525
spring.mail.username = 26248c87ebc455
spring.mail.password = 695594f47f9cac
spring.mail.properties.mais.smtp.auth = true
spring.mail.properties.mais.smtp.starttls.enable = true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher